In [246]:
import random
import numpy as np

def binToDecimal(x):
    return int(str(x), 2)

class AlgoritmoGenetico:
    def __init__(self, f , n):
        self.f = f
        self.n_poblacion = n
        self.crearPoblacion()
        self.x1 , self.x2 = self.Seleccion()
        self.Crossover()
        
    #Crea la poblacion de binarios aleatorios de 0 al 31
    #Devuelve un array con shape( n_poblacion , 5) en la que cada numero representa un bit
    def crearPoblacion(self):
            self.poblacion = np.random.randint(2, size= (self.n_poblacion,5))
            
            
            
    #Calcula el fitnest para cada individuo de la poblacion
    #Devuelve un array con el fitness con shape ()
    def calculateFitnest(self):
        #Paso los individuos de binario a decimal
        pesos = []
        for poblacion in self.poblacion:
            decimal = 0
            for i,number  in enumerate(reversed(poblacion)):
                decimal += (2 ** i) * number
            pesos.append(decimal)
        return np.array(pesos)
        
        
    # Calculo la probabilidad de los fitnest
    def calculateProbability(self):
            return np.array([individuo / np.sum(self.fitnest) for individuo in self.fitnest])
            
            
             
           
    #Seleccion los dos mejores individuos de la poblacion y devuelvo sus indices.
    def Seleccion(self):
        self.fitnest = self.calculateFitnest()
        print('\nFitnest de la poblacion \n \n', self.fitnest)
        self.probabilidades = self.calculateProbability()
        print('\nProbabilidad de la poblacion \n\n', self.probabilidades)
        #Me quedo con los mejores individuos de la poblacion
        x1 = np.argmax(self.probabilidades)
        self.probabilidades[x1] = 0
        x2 = np.argmax(self.probabilidades)
        print('\nIndices de los fitnest', x1,x2)
        return (x1, x2)
    
    def Crossover(self):
        #p1 y p2 son los puntos de cruce
        p1 = 3
        p2 = 4
        print('Elemento a cruzar')
        print(self.poblacion[self.x2] ,self.poblacion[self.x1])
        a = self.poblacion[self.x2,0:p1]
        b = self.poblacion[self.x1,p1:]
        c = np.concatenate((a,b) )
        print('Primer hijo creado')
        print(c)
        a = self.poblacion[self.x1,0:p1]
        b = self.poblacion[self.x2,p1:]
        c = np.concatenate((a,b) )
        print('Segundo hijo creado')
        print(c)
        a = self.poblacion[self.x1,0:p2]
        b = self.poblacion[self.x2,p2:]
        c = np.concatenate((a,b) )
        print('Tercero hijo creado')
        print(c)
        a = self.poblacion[self.x2,0:p2]
        b = self.poblacion[self.x1,p2:]
        c = np.concatenate((a,b) )
        print('Cuarto hijo creado')
        print(c)
            


In [247]:
def function(x1):
    return x1 + 5

alg = AlgoritmoGenetico(function,6)


Fitnest de la poblacion 
 
 [12 23 10  1  3  6]

Probabilidad de la poblacion 

 [0.21818182 0.41818182 0.18181818 0.01818182 0.05454545 0.10909091]

Indices de los fitnest 1 0
Elemento a cruzar
[0 1 1 0 0] [1 0 1 1 1]
Primer hijo creado
[0 1 1 1 1]
Segundo hijo creado
[1 0 1 0 0]
Tercero hijo creado
[1 0 1 1 0]
Cuarto hijo creado
[0 1 1 0 1]
