In [105]:
import random
import numpy as np

def binToDecimal(x):
    return int(str(x), 2)

def arrayBinToDecimal(poblacion):
        decimales = []
        for poblacion in poblacion:
            decimal = 0
            for i,number  in enumerate(reversed(poblacion)):
                decimal += (2 ** i) * number #Paso los individuos de binario a decimal
            decimales.append(decimal) 
        return decimales
    
def function(x1):
    return -(x1**2) + 30*x1 + 75

        
class AlgoritmoGenetico:
    def __init__(self, f , n):
        self.f = f
        self.n_poblacion = n
        
    def crearPoblacion(self):
        # Creamos poblacion de 5 bits es decir del rango [0,31]
        
        #self.poblacion = np.random.randint(2, size= (self.n_poblacion,5))
        self.poblacion = np.stack(([0,1,0,0,0],[0,0,0,1,0],[0,0,0,1,1],[1,1,1,1,1],[0,0,1,0,0]))
            
            
    def calculateFitnest(self):
        #Calcula el fitnest para cada individuo de la poblacion
        #Devuelve un array con el fitness con shape ()
        
        pesos = []
        self.decimales = []
        self.decimales = arrayBinToDecimal(self.poblacion)
        print('Binarios a decimales -- \n',self.decimales)
        pesos = np.array([self.f(xi) for xi in self.decimales])
        print('Pesos \n',pesos)
        return pesos
        

    def probability(self):
        # Calculo la probabilidad de los fitnest
        return np.array([individuo / np.sum(self.fitnest) for individuo in self.fitnest])
             
           
    def selectBest(self):
        #Seleccion los dos mejores individuos de la poblacion y devuelvo sus indices.
        self.fitnest = self.calculateFitnest()
        self.probabilidades = self.probability()
        print('Probabilidad de la poblacion \n', self.probabilidades)
        x1 = np.argmax(self.probabilidades)
        self.mejorIndividuo = self.poblacion[x1]
        self.probabilidades[x1] = 0
        x2 = np.argmax(self.probabilidades)
        if (x1 == x2):
            if (self.poblacion[x2,4] == 0):
                self.poblacion[x2,4] = 1
            else:
                self.poblacion[x2,4] = 0
        print('Indices de los mejores individuos \n', x1,x2)
        return (x1, x2)
    
    def crossover(self , sol1, sol2):
        #p1 y p2 son los puntos de cruce
        p1 = 3
        p2 = 4
        nuevaPoblacion = []
        print('\nElementos a cruzar \n',self.poblacion[self.x1] ,self.poblacion[self.x2])
        c = np.concatenate((sol2[0:p1],sol1[p1:]))
        nuevaPoblacion.append(c)
        c = np.concatenate((sol1[0:p1],sol2[p1:]))
        nuevaPoblacion.append(c)
        c = np.concatenate((sol1[0:p2],sol2[p2:]))
        nuevaPoblacion.append(c)
        c = np.concatenate((sol2[0:p2],sol1[p2:]))
        nuevaPoblacion.append(c)
        #Agrego a la nueva poblacion los dos mejores individuos
        return nuevaPoblacion
    
    
    
    def mutacion(self,probabilidad = 0.5):
        #Cambiamos el 2 bit del tercer hijo.
        
        if (random.uniform(0,1) > probabilidad):
            if (self.poblacion[2,3] == 0):
                self.poblacion[2,3] = 1
            else:
                self.poblacion[2,3] = 0
                
                
    def calcular(self):
        self.crearPoblacion()
        for i in range(3000):
            print("ITERACION NRO:", i)
            print('LA POBLACION ES \n',self.poblacion)
            
            self.x1 , self.x2 = self.selectBest()
            nuevaPoblacion = self.crossover(self.poblacion[self.x1],self.poblacion[self.x2])
            nuevaPoblacion.append(self.poblacion[self.x1])
            nuevaPoblacion.append(self.poblacion[self.x2])
            nuevaPoblacion = np.vstack(nuevaPoblacion)
            self.poblacion = nuevaPoblacion
            print('LA NUEVA POBLACION ES \n',self.poblacion)
            print('El mejor individuo es = ',self.decimales[self.x1])
            print(' ------------------------------------------- \n')
            self.mutacion()
            
        


In [106]:
alg = AlgoritmoGenetico(function,6)
alg.calcular()

ITERACION NRO: 0
LA POBLACION ES 
 [[0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]
Binarios a decimales -- 
 [8, 2, 3, 31, 4]
Pesos 
 [251 131 156  44 179]
Probabilidad de la poblacion 
 [0.32982917 0.17214192 0.20499343 0.05781866 0.23521682]
Indices de los mejores individuos 
 0 4

Elementos a cruzar 
 [0 1 0 0 0] [0 0 1 0 0]
LA NUEVA POBLACION ES 
 [[0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
El mejor individuo es =  8
 ------------------------------------------- 

ITERACION NRO: 1
LA POBLACION ES 
 [[0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
Binarios a decimales -- 
 [4, 8, 10, 4, 8, 4]
Pesos 
 [179 251 275 179 251 179]
Probabilidad de la poblacion 
 [0.13622527 0.19101979 0.20928463 0.13622527 0.19101979 0.13622527]
Indices de los mejores individuos 
 2 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 0 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0

El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 120
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 121
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 

LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 200
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 201
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.154

 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 287
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 288
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabi

 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 388
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ----------------------

 ------------------------------------------- 

ITERACION NRO: 477
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 478
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NU

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 544
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 545
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [

 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 644
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 645
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabi

 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 716
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 717
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.169

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 798
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 799
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 

LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 892
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 893
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15

 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 993
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 994
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probab

 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1078
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1079
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Prob

 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1168
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1263
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1264
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]


El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1357
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1358
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 


ITERACION NRO: 1432
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1433
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1520
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1521
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]

 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1596
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1597
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [

El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1691
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1692
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar

 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1802
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1803
LA POBLACION ES 
 [[0 1 0

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1891
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1892
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]


 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1977
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 1978
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Proba

LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2072
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2073
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0


ITERACION NRO: 2167
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2168
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2275
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2276
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]

 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2381
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 --------------------

 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2465
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2466
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [

 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2575
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2576
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elem

El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2667
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2668
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 


ITERACION NRO: 2762
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2763
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]

 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2858
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Probabilidad de la poblacion 
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2859
LA POBLACION ES 
 [[0 1 0

 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2953
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 8, 10, 10, 10]
Pesos 
 [275 275 251 275 275 275]
Probabilidad de la poblacion 
 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]
Indices de los mejores individuos 
 0 1

Elementos a cruzar 
 [0 1 0 1 0] [0 1 0 1 0]
LA NUEVA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es =  10
 ------------------------------------------- 

ITERACION NRO: 2954
LA POBLACION ES 
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Binarios a decimales -- 
 [10, 10, 10, 10, 10, 10]
Pesos 
 [275 275 275 275 275 275]
Proba