In [388]:
import random
import numpy as np

def binToDecimal(x):
    return int(str(x), 2)

class AlgoritmoGenetico:
    def __init__(self, f , n):
        self.f = f
        self.n_poblacion = n
        
        
    # Creamos poblacion de 5 bits es decir del rango [0,31]
    
    def crearPoblacion(self):
            #self.poblacion = np.random.randint(2, size= (self.n_poblacion,5))
            self.poblacion = np.stack(([0,1,0,0,0],[0,0,0,1,0],[0,0,0,1,1],[1,1,1,1,1],[0,0,1,0,0]))
            
            
    #Calcula el fitnest para cada individuo de la poblacion
    #Devuelve un array con el fitness con shape ()
    def calculateFitnest(self):
        pesos = []
        self.decimales = []
        for poblacion in self.poblacion:
            decimal = 0
            for i,number  in enumerate(reversed(poblacion)):
                decimal += (2 ** i) * number #Paso los individuos de binario a decimal
            self.decimales.append(decimal) 
            pesos.append(self.f(decimal))
        return np.array(pesos)
        
        
    # Calculo la probabilidad de los fitnest
    def calculateProbability(self):
            return np.array([individuo / np.sum(self.fitnest) for individuo in self.fitnest])
             
           
    #Seleccion los dos mejores individuos de la poblacion y devuelvo sus indices.
    def Seleccion(self):
        self.fitnest = self.calculateFitnest()
        self.probabilidades = self.calculateProbability()
        print('\nProbabilidad de la poblacion \n\n', self.probabilidades)
        x1 = np.argmax(self.probabilidades)
        self.mejorIndividuo = self.poblacion[x1]
        self.probabilidades[x1] = 0
        x2 = np.argmax(self.probabilidades)
        if (x1 == x2):
            if (self.poblacion[x2,4] == 0):
                self.poblacion[x2,4] = 1
            else:
                self.poblacion[x2,4] = 0
        return (x1, x2)
    
    def Crossover(self):
        #p1 y p2 son los puntos de cruce
        p1 = 3
        p2 = 4
        nuevaPoblacion = []
        print('\nElementos a cruzar')
        print(self.poblacion[self.x1] ,self.poblacion[self.x2])
        a = self.poblacion[self.x2,0:p1]
        b = self.poblacion[self.x1,p1:]
        c = np.concatenate((a,b))
        nuevaPoblacion.append(c)
        print('Primer hijo creado')
        print(c)
        a = self.poblacion[self.x1,0:p1]
        b = self.poblacion[self.x2,p1:]
        c = np.concatenate((a,b) )
        nuevaPoblacion.append(c)
        print('Segundo hijo creado')
        print(c)
        a = self.poblacion[self.x1,0:p2]
        b = self.poblacion[self.x2,p2:]
        c = np.concatenate((a,b) )
        nuevaPoblacion.append(c)
        print('Tercero hijo creado')
        print(c)
        a = self.poblacion[self.x2,0:p2]
        b = self.poblacion[self.x1,p2:]
        c = np.concatenate((a,b) )
        nuevaPoblacion.append(c)
        print('Cuarto hijo creado')
        print(c)
        #Agrego a la nueva poblacion los dos mejores individuos
        nuevaPoblacion.append(self.poblacion[self.x1])
        nuevaPoblacion.append(self.poblacion[self.x2])
        nuevaPoblacion = np.vstack(nuevaPoblacion)
        return nuevaPoblacion
    
    
    #Cambiamos el 2 bit del tercer hijo.
    
    def Mutacion(self,probabilidad = 0.5):
        print(random.uniform(0,1))
        if (random.uniform(0,1) > probabilidad):
            if (self.poblacion[2,3] == 0):
                self.poblacion[2,3] = 1
            else:
                self.poblacion[2,3] = 0
                
                
    def calcular(self):
        self.crearPoblacion()
        for i in range(3000):
            print("ITERACION NRO:",i)
            print('LA POBLACION ES')
            print(self.poblacion)
            self.x1 , self.x2 = self.Seleccion()
            print('\nFitnest de la poblacion \n \n', self.fitnest)
            print('\nIndices de los fitnest',self.x1, self.x2)
            self.poblacion = self.Crossover()
            print('LA NUEVA POBLACION ES')
            print(self.poblacion)
            print('El mejor individuo es ',self.decimales[self.x1])
            self.Mutacion()
            
        


In [389]:
def function(x1):
    return -(x1**2) + 30*x1 + 75

alg = AlgoritmoGenetico(function,6)
alg.calcular()

ITERACION NRO: 0
LA POBLACION ES
[[0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]

Probabilidad de la poblacion 

 [0.32982917 0.17214192 0.20499343 0.05781866 0.23521682]

Fitnest de la poblacion 
 
 [251 131 156  44 179]

Indices de los fitnest 0 4

Elementos a cruzar
[0 1 0 0 0] [0 0 1 0 0]
Primer hijo creado
[0 0 1 0 0]
Segundo hijo creado
[0 1 0 0 0]
Tercero hijo creado
[0 1 0 0 0]
Cuarto hijo creado
[0 0 1 0 0]
LA NUEVA POBLACION ES
[[0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
El mejor individuo es  8
0.5903321280919398
ITERACION NRO: 1
LA POBLACION ES
[[0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]

Probabilidad de la poblacion 

 [0.13875969 0.19457364 0.19457364 0.13875969 0.19457364 0.13875969]

Fitnest de la poblacion 
 
 [179 251 251 179 251 179]

Indices de los fitnest 1 2

Elementos a cruzar
[0 1 0 0 0] [0 1 0 0 0]
Primer hijo creado
[0 1 0 0 0]
Segundo hijo creado
[0 1 0 0 0]
Tercero hijo c

[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.6233521733477291
ITERACION NRO: 79
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.41303587093015237
ITERACION NRO: 80
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912

LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.4183200655618424
ITERACION NRO: 146
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.8049881399454283
ITERACION NRO: 147
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 


Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.6744712796959969
ITERACION NRO: 224
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.0891

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.07037567402009792
ITERACION NRO: 297
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [

El mejor individuo es  10
0.9794513748422702
ITERACION NRO: 363
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7481135479896804
ITERACION NRO: 364
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]

ITERACION NRO: 405
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.27471070868448744
ITERACION NRO: 406
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo

Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.009199594425402968
ITERACION NRO: 461
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.15024333156260572
ITERACION NRO: 462
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0

Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.91445710921771
ITERACION NRO: 535
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.2964260233011087
ITERACION NRO: 536
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 

[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.38511875985622346
ITERACION NRO: 609
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.12081270558329738
ITERACION NRO: 610
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16

LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.09571098124299338
ITERACION NRO: 701
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]

Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.6209865565903345
ITERACION NRO: 757
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.9702466798591314
ITERACION NRO: 758
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.1691

[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.3960890656942827
ITERACION NRO: 838
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.4779805493388486
ITERACION NRO: 839
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0

[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.4798537520318338
ITERACION NRO: 909
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.26435427872575
ITERACION NRO: 910
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912

[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.8309822686892911
ITERACION NRO: 984
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.5890432722808112
ITERACION NRO: 985
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.169

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.24628492372339506
ITERACION NRO: 1061
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.4666438479922058
ITERACION NRO: 1140
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [

LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.4894234449193463
ITERACION NRO: 1202
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]

Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.48701748232201003
ITERACION NRO: 1270
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.3294926031321377
ITERACION NRO: 1271
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16

Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.07642160914439433
ITERACION NRO: 1337
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.5432746814220049
ITERACION NRO: 1338
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacio

[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.6841366544132673
ITERACION NRO: 1409
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.9192017741164968
ITERACION NRO: 1410
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 

[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.8831797549387851
ITERACION NRO: 1497
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.23158613515319326
ITERACION NRO: 1498
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 27

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.4270521825083956
ITERACION NRO: 1572
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.3002372896382245
ITERACION NRO: 1573
LA POBLACION ES
[[0 1 

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.3957650945153559
ITERACION NRO: 1646
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.753308326809606
ITERACION NRO: 1647
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1

[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7443699769284168
ITERACION NRO: 1720
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.6629619483868543
ITERACION NRO: 1721
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 

Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.28164130264874254
ITERACION NRO: 1794
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7138609114540202
ITERACION NRO: 1795
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0

Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.175044351270929
ITERACION NRO: 1868
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7271607354771616
ITERACION NRO: 1869
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.6605998167788723
ITERACION NRO: 1942
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.11184818984183176
ITERACION NRO: 1943
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.1

[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.5416312852432825
ITERACION NRO: 2025
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.30830719273453777
ITERACION NRO: 2026
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.

[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.5873753352770931
ITERACION NRO: 2102
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.40452443444794284
ITERACION NRO: 2103
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.

[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.4800452465412417
ITERACION NRO: 2181
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.48492887185069977
ITERACION NRO: 2182
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]


Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.9499272288793275
ITERACION NRO: 2257
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.33867915343011856
ITERACION NRO: 2258
LA POBLACION ES
[[0 1

Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.10478653874912325
ITERACION NRO: 2341
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.3312724462721973
ITERACION NRO: 2342
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15

[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.264492264443857
ITERACION NRO: 2420
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.1850833728001816
ITERACION NRO: 2421
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de l

ITERACION NRO: 2497
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.08885949127444559
ITERACION NRO: 2498
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hi

 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.5303178208085335
ITERACION NRO: 2572
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACIO

[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7772121265936159
ITERACION NRO: 2651
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.5985834836436034
ITERACION NRO: 2652
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.44297944955981405
ITERACION NRO: 2731
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.19455916979243204
ITERACION NRO: 2732
LA POBLACION ES
[[0 

ITERACION NRO: 2788
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7630357004148459
ITERACION NRO: 2789
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hij


Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7508787248975686
ITERACION NRO: 2862
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]

Fitnest de la poblacion 
 
 [275 275 275 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.2184536341274197
ITERACION NRO: 2863
LA POBLACION ES
[[0 1

[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.7425250877047603
ITERACION NRO: 2924
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.00741621990525787
ITERACION NRO: 2925
LA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]

Probabilidad de la poblacion 

 [0.16912669 0.1

 [0.16912669 0.16912669 0.15436654 0.16912669 0.16912669 0.16912669]

Fitnest de la poblacion 
 
 [275 275 251 275 275 275]

Indices de los fitnest 0 1

Elementos a cruzar
[0 1 0 1 0] [0 1 0 1 0]
Primer hijo creado
[0 1 0 1 0]
Segundo hijo creado
[0 1 0 1 0]
Tercero hijo creado
[0 1 0 1 0]
Cuarto hijo creado
[0 1 0 1 0]
LA NUEVA POBLACION ES
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
El mejor individuo es  10
0.9888378474523516
